In [2]:
import numpy as np
import pandas as pd

In [3]:
import seaborn as sb
import matplotlib.pyplot as plt

In [4]:
import cv2
import glob as gb

In [5]:
img_path = gb.glob('Pics/*.*')

In [6]:
img_path

['Pics\\2 (4).png',
 'Pics\\astronaut.jpg',
 'Pics\\bike.jpg',
 'Pics\\color_dance.jpg',
 'Pics\\combined.png',
 'Pics\\girls.jpg',
 'Pics\\HSV_ColorSpace.jpg',
 'Pics\\HSV_ColorSpace2.jpg',
 'Pics\\Img_merged_BGR.jpg',
 'Pics\\Img_merged_RGB.jpg',
 'Pics\\Overlay.png',
 'Pics\\rainbow.png']

In [7]:
image = cv2.imread("Pics/bike.jpg")

In [8]:
image.shape

(520, 780, 3)

In [9]:
image

array([[[176, 179, 177],
        [178, 181, 179],
        [180, 183, 181],
        ...,
        [193, 182, 178],
        [193, 182, 178],
        [193, 182, 178]],

       [[177, 178, 176],
        [178, 179, 177],
        [181, 182, 180],
        ...,
        [193, 182, 178],
        [193, 182, 178],
        [193, 182, 178]],

       [[176, 177, 175],
        [178, 179, 177],
        [180, 181, 179],
        ...,
        [193, 182, 178],
        [193, 182, 178],
        [193, 182, 178]],

       ...,

       [[ 79, 100, 121],
        [ 96, 120, 140],
        [ 37,  61,  81],
        ...,
        [  5,  13,  36],
        [ 42,  50,  73],
        [ 47,  55,  78]],

       [[ 84, 105, 126],
        [110, 134, 154],
        [ 54,  78,  98],
        ...,
        [  3,  10,  35],
        [ 15,  22,  47],
        [ 38,  45,  70]],

       [[ 67,  88, 109],
        [ 66,  90, 110],
        [ 56,  80, 100],
        ...,
        [ 58,  65,  90],
        [ 44,  51,  76],
        [ 14,  21,  46]]

In [10]:
image[0].shape

(780, 3)

In [11]:
pixel_value = image[100, 200]
pixel_value

array([183, 169, 157], dtype=uint8)

In [12]:
image[100, 200]

array([183, 169, 157], dtype=uint8)

In [13]:
image[100, 200][0], image[100, 200][1], image[100, 200][2]

(183, 169, 157)

In [14]:
blue = image[..., 0]
green = image[..., 1]
red = image[..., 2]

In [15]:
blue

array([[176, 178, 180, ..., 193, 193, 193],
       [177, 178, 181, ..., 193, 193, 193],
       [176, 178, 180, ..., 193, 193, 193],
       ...,
       [ 79,  96,  37, ...,   5,  42,  47],
       [ 84, 110,  54, ...,   3,  15,  38],
       [ 67,  66,  56, ...,  58,  44,  14]], dtype=uint8)

In [16]:
blue.shape

(520, 780)

In [17]:
green

array([[179, 181, 183, ..., 182, 182, 182],
       [178, 179, 182, ..., 182, 182, 182],
       [177, 179, 181, ..., 182, 182, 182],
       ...,
       [100, 120,  61, ...,  13,  50,  55],
       [105, 134,  78, ...,  10,  22,  45],
       [ 88,  90,  80, ...,  65,  51,  21]], dtype=uint8)

In [18]:
green.shape

(520, 780)

In [19]:
red

array([[177, 179, 181, ..., 178, 178, 178],
       [176, 177, 180, ..., 178, 178, 178],
       [175, 177, 179, ..., 178, 178, 178],
       ...,
       [121, 140,  81, ...,  36,  73,  78],
       [126, 154,  98, ...,  35,  47,  70],
       [109, 110, 100, ...,  90,  76,  46]], dtype=uint8)

In [20]:
red.shape

(520, 780)

In [21]:
cv2.imshow("Blue channel", blue)
cv2.imshow("Green channel", green)
cv2.imshow("Red channel", red)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
cv2.imshow("Original image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
image_gray = cv2.imread("Pics/bike.jpg", 0)
cv2.imshow("Gray Mode", image_gray)
cv2.waitKey()
cv2.destroyAllWindows()

In [24]:
img_astro = cv2.imread("Pics/astronaut.jpg")
img_astro.shape

(1143, 2000, 3)

In [30]:
img_astro = cv2.imread("Pics/astronaut.jpg")
print('Main image doordinate:', img_astro.shape)
cv2.imshow("Main image astro", img_astro)
cv2.waitKey()
cv2.destroyAllWindows()

for i in range(3):
    img_astro = img_astro [::2, ::2, :]

    cv2.imshow(f'Pic_resize {i}', img_astro)
    print(f'Resize {i} image coordinate:', img_astro.shape)
    cv2.waitKey()
    cv2.destroyAllWindows()

Main image doordinate: (1143, 2000, 3)
Resize 0 image coordinate: (572, 1000, 3)
Resize 1 image coordinate: (286, 500, 3)
Resize 2 image coordinate: (143, 250, 3)


In [61]:
img_bike = cv2.imread('Pics/bike.jpg', 1)
print("Main coordinate:", img_bike.shape)
cv2.imshow('Main image', img_bike)
img_resized = cv2.resize(img_bike, (1200, 800))
cv2.imshow('Resized image', img_resized)
cv2.setWindowProperty('Main image', cv2.WND_PROP_TOPMOST, 1)

cv2.waitKey()
cv2.destroyAllWindows()

Main coordinate: (520, 780, 3)


In [41]:
img_resized.shape

(800, 1200, 3)

In [55]:
img = img_bike[:, ::3, :]
cv2.imshow('Image_resize_3', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [56]:
img.shape

(520, 260, 3)